version: '3'
services:
  db:
    image: "apache/couchdb"
  app:
    build: .
    environment:
      - COUCHDB_URL=http://db:5984
    links:
      - "db"
    depends_on:
      - "db"
  dbconfig:
    build: .
    entrypoint: "node ./src/js/db/dbSetup.js"
    environment:
      - COUCHDB_URL=http://db:5984
    links:
      - "db"
    depends_on:
      - "db"
