version: '3'
services:
  app:
    image: "sjrk/story-telling-server"
    ports:
      - "8081:8081"
    links:
      - "db"
    depends_on:
      - "db"
    environment:
      - COUCHDB_URL=http://db:5984
  db:
    image: "klaemo/couchdb"
    ports:
      - "5984:5984"
  dbConfig:
    image: "sjrk/story-telling-server"
    environment:
      - COUCHDB_URL=http://db:5984
    depends_on:
      - "db"
    links:
      - "db"
    entrypoint: "node ./src/js/dbSetup.js"    
